models:
- alias: default
  kwargs:
    n: 1
    temperature: 0
  model: gemini/gemini-2.0-flash
  timeout: 120
- alias: gemini-llm-for-chart
  kwargs:
    n: 1
    response_format:
      type: json_object
    temperature: 0
  model: gemini/gemini-2.0-flash
  timeout: 120
provider: litellm_llm
type: llm
---
models:
- alias: default
  model: gemini/text-embedding-004
  timeout: 120
provider: litellm_embedder
type: embedder
---
endpoint: http://localhost:3000
provider: wren_ui
type: engine
---
endpoint: http://localhost:8000
provider: wren_ibis
type: engine
---
embedding_model_dim: 768
location: http://localhost:6333
provider: qdrant
recreate_index: true
timeout: 120
type: document_store
---
pipes:
- document_store: qdrant
  embedder: litellm_embedder.default
  name: db_schema_indexing
- document_store: qdrant
  embedder: litellm_embedder.default
  name: historical_question_indexing
- document_store: qdrant
  embedder: litellm_embedder.default
  name: table_description_indexing
- document_store: qdrant
  embedder: litellm_embedder.default
  llm: litellm_llm.default
  name: db_schema_retrieval
- document_store: qdrant
  embedder: litellm_embedder.default
  name: historical_question_retrieval
- engine: wren_ui
  llm: litellm_llm.default
  name: sql_generation
- engine: wren_ui
  llm: litellm_llm.default
  name: sql_correction
- engine: wren_ui
  llm: litellm_llm.default
  name: followup_sql_generation
- llm: litellm_llm.default
  name: sql_answer
- llm: litellm_llm.default
  name: semantics_description
- engine: wren_ui
  llm: litellm_llm.default
  name: relationship_recommendation
- llm: litellm_llm.default
  name: question_recommendation
- document_store: qdrant
  embedder: litellm_embedder.default
  llm: litellm_llm.default
  name: question_recommendation_db_schema_retrieval
- engine: wren_ui
  llm: litellm_llm.default
  name: question_recommendation_sql_generation
- llm: litellm_llm.gemini-llm-for-chart
  name: chart_generation
- llm: litellm_llm.gemini-llm-for-chart
  name: chart_adjustment
- document_store: qdrant
  embedder: litellm_embedder.default
  llm: litellm_llm.default
  name: intent_classification
- llm: litellm_llm.default
  name: misleading_assistance
- llm: litellm_llm.default
  name: data_assistance
- document_store: qdrant
  embedder: litellm_embedder.default
  name: sql_pairs_indexing
- document_store: qdrant
  embedder: litellm_embedder.default
  llm: litellm_llm.default
  name: sql_pairs_retrieval
- llm: litellm_llm.default
  name: preprocess_sql_data
- engine: wren_ui
  name: sql_executor
- llm: litellm_llm.default
  name: user_guide_assistance
- llm: litellm_llm.default
  name: sql_question_generation
- llm: litellm_llm.default
  name: sql_generation_reasoning
- llm: litellm_llm.default
  name: followup_sql_generation_reasoning
- engine: wren_ui
  llm: litellm_llm.default
  name: sql_regeneration
- document_store: qdrant
  embedder: litellm_embedder.default
  name: instructions_indexing
- document_store: qdrant
  embedder: litellm_embedder.default
  name: instructions_retrieval
- document_store: qdrant
  engine: wren_ibis
  name: sql_functions_retrieval
- document_store: qdrant
  name: project_meta_indexing
type: pipeline
---
settings:
  allow_intent_classification: true
  allow_sql_generation_reasoning: true
  column_indexing_batch_size: 50
  development: true
  enable_column_pruning: false
  engine_timeout: 30
  historical_question_retrieval_similarity_threshold: 0.9
  instructions_similarity_threshold: 0.7
  instructions_top_k: 10
  langfuse_enable: true
  langfuse_host: https://cloud.langfuse.com
  logging_level: DEBUG
  query_cache_maxsize: 1000
  query_cache_ttl: 3600
  sql_pairs_retrieval_max_size: 10
  sql_pairs_similarity_threshold: 0.7
  table_column_retrieval_size: 100
  table_retrieval_size: 10
